from . import academic_year
from . import level
from . import classroom
from . import subject
from . import teacher
from . import student
from . import parent
from . import student_document
from . import exam
from . import exam_result
from . import subject_assignment
from . import fee_type
from . import student_fee
from . import fee_payment
from . import res_partner
